### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by Zainab-e** [jaimelias/CF7PD#1]
Hi!
I found some data which needs correction. Can you please rectify it:
![image](https://user-images.githubusercontent.com/43878472/50814877-f15ed400-133c-11e9-9d6b-6d4ea8d075e2.png)
ipgeolocation's free plan does not have 1000 requests, it has 50,000 request limit and the paid plans start from $15. PLease edit the mentioned info.

**Comment by jaimelias** [comment]
Thanks for the update. Solved!
